site_name: DEVELOPER HUB
theme:
  name: material
  font:
    text: Roboto
  logo: assets/flag_black_white_low.jpg
  favicon: assets/normal-reproduction-low-resolution.jpg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer

markdown_extensions:
  - footnotes
  - tables
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html

extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search
  - multirepo:
      cleanup: true
      keep_docs_dir: false
      nav_repos:
        - name: eudi-doc-architecture-and-reference-framework
          import_url: 'https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework?multi_docs=True&branch=main&edit_uri=/blob/main/'
          imports:
            - '**/*.md'
        - name: eudi-web-booking-service-demo
          import_url: 'https://github.com/eu-digital-identity-wallet/eudi-web-booking-service-demo?multi_docs=True&branch=main&edit_uri=/blob/main/'
          imports:
            - '**/*.md'
        - name: eudi-app-android-wallet-ui
          import_url: 'https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui?multi_docs=True&branch=main'
          imports:
            - '**/*.md'
        - name: eudi-app-ios-wallet-ui
          import_url: 'https://github.com/eu-digital-identity-wallet/eudi-app-ios-wallet-ui?multi_docs=True&branch=main'
          imports:
            - '**/*.md'

nav:
  - Getting started:
      - Home: eudi-doc-architecture-and-reference-framework/README.md
      - Contributing: eudi-doc-architecture-and-reference-framework/CONTRIBUTING.md
  - The Wallet’s specifications:
      - Architecture Reference Framework (ARF): eudi-doc-architecture-and-reference-framework/docs/arf.md
  - Use Cases:
      - Travel Scenario: eudi-web-booking-service-demo/README.md
  - A first look at the wallet:
      - Android application: eudi-app-android-wallet-ui/README.md
      - iOS application: eudi-app-ios-wallet-ui/README.md
  - Roadmap: roadmap.md
  - Code of Conduct: code-of-conduct.md
  - Developer tools to build wallets and applications: developer-tools.md
#    - Introduction: eudi-doc-architecture-and-reference-framework/
  - Trust model & accreditation of actors: trust-model.md
